/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminBuilderRouteImport } from './routes/admin.builder'
import { Route as AdminEvidenceRouteImport } from './routes/admin.evidence'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProcessesRouteImport } from './routes/admin.processes'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminTrainingsRouteImport } from './routes/admin.trainings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppDeliveriesRouteImport } from './routes/app.deliveries'
import { Route as AppProcessesRouteImport } from './routes/app.processes'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as LoginManagerRouteImport } from './routes/login.manager'
import { Route as AdminExecutionIdRouteImport } from './routes/admin.execution.$id'
import { Route as AdminRestaurantsIndexRouteImport } from './routes/admin.restaurants.index'
import { Route as AdminRestaurantsIdRouteImport } from './routes/admin.restaurants.$id'
import { Route as AppProcessIdRouteImport } from './routes/app.process.$id'
import { Route as AppTaskIdRouteImport } from './routes/app.task.$id'
import { Route as AppTrainingIdRouteImport } from './routes/app.training.$id'
import { Route as AppTrainingsIndexRouteImport } from './routes/app.trainings.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvidenceRoute = AdminEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessesRoute = AdminProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingsRoute = AdminTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessesRoute = AppProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginManagerRoute = LoginManagerRouteImport.update({
  id: '/login/manager',
  path: '/login/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExecutionIdRoute = AdminExecutionIdRouteImport.update({
  id: '/execution/$id',
  path: '/execution/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsIndexRoute = AdminRestaurantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRestaurantsRoute,
} as any)
const AdminRestaurantsIdRoute = AdminRestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRestaurantsRoute,
} as any)
const AppProcessIdRoute = AppProcessIdRouteImport.update({
  id: '/process/$id',
  path: '/process/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskIdRoute = AppTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingIdRoute = AppTrainingIdRouteImport.update({
  id: '/training/$id',
  path: '/training/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingsIndexRoute = AppTrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/processes': typeof AdminProcessesRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/chat': typeof AppChatRoute
  '/app/deliveries': typeof AppDeliveriesRoute
  '/app/processes': typeof AppProcessesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/manager': typeof LoginManagerRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/execution/$id': typeof AdminExecutionIdRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/app/process/$id': typeof AppProcessIdRoute
  '/app/task/$id': typeof AppTaskIdRoute
  '/app/training/$id': typeof AppTrainingIdRoute
  '/admin/restaurants/': typeof AdminRestaurantsIndexRoute
  '/app/trainings/': typeof AppTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/processes': typeof AdminProcessesRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/chat': typeof AppChatRoute
  '/app/deliveries': typeof AppDeliveriesRoute
  '/app/processes': typeof AppProcessesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/manager': typeof LoginManagerRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/execution/$id': typeof AdminExecutionIdRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/app/process/$id': typeof AppProcessIdRoute
  '/app/task/$id': typeof AppTaskIdRoute
  '/app/training/$id': typeof AppTrainingIdRoute
  '/admin/restaurants': typeof AdminRestaurantsIndexRoute
  '/app/trainings': typeof AppTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/evidence': typeof AdminEvidenceRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/processes': typeof AdminProcessesRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/chat': typeof AppChatRoute
  '/app/deliveries': typeof AppDeliveriesRoute
  '/app/processes': typeof AppProcessesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/manager': typeof LoginManagerRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/execution/$id': typeof AdminExecutionIdRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/app/process/$id': typeof AppProcessIdRoute
  '/app/task/$id': typeof AppTaskIdRoute
  '/app/training/$id': typeof AppTrainingIdRoute
  '/admin/restaurants/': typeof AdminRestaurantsIndexRoute
  '/app/trainings/': typeof AppTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/unauthorized'
    | '/admin/alerts'
    | '/admin/builder'
    | '/admin/evidence'
    | '/admin/groups'
    | '/admin/orders'
    | '/admin/processes'
    | '/admin/restaurants'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/chat'
    | '/app/deliveries'
    | '/app/processes'
    | '/app/profile'
    | '/app/tasks'
    | '/login/admin'
    | '/login/manager'
    | '/admin/'
    | '/app/'
    | '/admin/execution/$id'
    | '/admin/restaurants/$id'
    | '/app/process/$id'
    | '/app/task/$id'
    | '/app/training/$id'
    | '/admin/restaurants/'
    | '/app/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/admin/alerts'
    | '/admin/builder'
    | '/admin/evidence'
    | '/admin/groups'
    | '/admin/orders'
    | '/admin/processes'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/chat'
    | '/app/deliveries'
    | '/app/processes'
    | '/app/profile'
    | '/app/tasks'
    | '/login/admin'
    | '/login/manager'
    | '/admin'
    | '/app'
    | '/admin/execution/$id'
    | '/admin/restaurants/$id'
    | '/app/process/$id'
    | '/app/task/$id'
    | '/app/training/$id'
    | '/admin/restaurants'
    | '/app/trainings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/unauthorized'
    | '/admin/alerts'
    | '/admin/builder'
    | '/admin/evidence'
    | '/admin/groups'
    | '/admin/orders'
    | '/admin/processes'
    | '/admin/restaurants'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/chat'
    | '/app/deliveries'
    | '/app/processes'
    | '/app/profile'
    | '/app/tasks'
    | '/login/admin'
    | '/login/manager'
    | '/admin/'
    | '/app/'
    | '/admin/execution/$id'
    | '/admin/restaurants/$id'
    | '/app/process/$id'
    | '/app/task/$id'
    | '/app/training/$id'
    | '/admin/restaurants/'
    | '/app/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginManagerRoute: typeof LoginManagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evidence': {
      id: '/admin/evidence'
      path: '/evidence'
      fullPath: '/admin/evidence'
      preLoaderRoute: typeof AdminEvidenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/processes': {
      id: '/admin/processes'
      path: '/processes'
      fullPath: '/admin/processes'
      preLoaderRoute: typeof AdminProcessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainings': {
      id: '/admin/trainings'
      path: '/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AdminTrainingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliveries': {
      id: '/app/deliveries'
      path: '/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processes': {
      id: '/app/processes'
      path: '/processes'
      fullPath: '/app/processes'
      preLoaderRoute: typeof AppProcessesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/manager': {
      id: '/login/manager'
      path: '/login/manager'
      fullPath: '/login/manager'
      preLoaderRoute: typeof LoginManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/execution/$id': {
      id: '/admin/execution/$id'
      path: '/execution/$id'
      fullPath: '/admin/execution/$id'
      preLoaderRoute: typeof AdminExecutionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants/': {
      id: '/admin/restaurants/'
      path: '/'
      fullPath: '/admin/restaurants/'
      preLoaderRoute: typeof AdminRestaurantsIndexRouteImport
      parentRoute: typeof AdminRestaurantsRoute
    }
    '/admin/restaurants/$id': {
      id: '/admin/restaurants/$id'
      path: '/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AdminRestaurantsIdRouteImport
      parentRoute: typeof AdminRestaurantsRoute
    }
    '/app/process/$id': {
      id: '/app/process/$id'
      path: '/process/$id'
      fullPath: '/app/process/$id'
      preLoaderRoute: typeof AppProcessIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/task/$id': {
      id: '/app/task/$id'
      path: '/task/$id'
      fullPath: '/app/task/$id'
      preLoaderRoute: typeof AppTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/$id': {
      id: '/app/training/$id'
      path: '/training/$id'
      fullPath: '/app/training/$id'
      preLoaderRoute: typeof AppTrainingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trainings/': {
      id: '/app/trainings/'
      path: '/trainings'
      fullPath: '/app/trainings/'
      preLoaderRoute: typeof AppTrainingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRestaurantsRouteChildren {
  AdminRestaurantsIdRoute: typeof AdminRestaurantsIdRoute
  AdminRestaurantsIndexRoute: typeof AdminRestaurantsIndexRoute
}

const AdminRestaurantsRouteChildren: AdminRestaurantsRouteChildren = {
  AdminRestaurantsIdRoute: AdminRestaurantsIdRoute,
  AdminRestaurantsIndexRoute: AdminRestaurantsIndexRoute,
}

const AdminRestaurantsRouteWithChildren =
  AdminRestaurantsRoute._addFileChildren(AdminRestaurantsRouteChildren)

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminBuilderRoute: typeof AdminBuilderRoute
  AdminEvidenceRoute: typeof AdminEvidenceRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProcessesRoute: typeof AdminProcessesRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRouteWithChildren
  AdminTrainingsRoute: typeof AdminTrainingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExecutionIdRoute: typeof AdminExecutionIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminBuilderRoute: AdminBuilderRoute,
  AdminEvidenceRoute: AdminEvidenceRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProcessesRoute: AdminProcessesRoute,
  AdminRestaurantsRoute: AdminRestaurantsRouteWithChildren,
  AdminTrainingsRoute: AdminTrainingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminExecutionIdRoute: AdminExecutionIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChatRoute: typeof AppChatRoute
  AppDeliveriesRoute: typeof AppDeliveriesRoute
  AppProcessesRoute: typeof AppProcessesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProcessIdRoute: typeof AppProcessIdRoute
  AppTaskIdRoute: typeof AppTaskIdRoute
  AppTrainingIdRoute: typeof AppTrainingIdRoute
  AppTrainingsIndexRoute: typeof AppTrainingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChatRoute: AppChatRoute,
  AppDeliveriesRoute: AppDeliveriesRoute,
  AppProcessesRoute: AppProcessesRoute,
  AppProfileRoute: AppProfileRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppProcessIdRoute: AppProcessIdRoute,
  AppTaskIdRoute: AppTaskIdRoute,
  AppTrainingIdRoute: AppTrainingIdRoute,
  AppTrainingsIndexRoute: AppTrainingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginManagerRoute: LoginManagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
